name: Analyse de Sécurité (Bandit & SonarQube)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # Job 1: Scan rapide avec Bandit
  bandit-scan:
    name: Scan SAST avec Bandit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      - name: Installation de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit
      # On ajoute "|| true" pour que le pipeline continue même si Bandit trouve des failles
      # Cela permet au job SonarQube de s'exécuter pour qu'on puisse voir son rapport
      - name: Lancement de l'analyse statique avec Bandit
        run: bandit -r . -l low || true

  # Job 2: Analyse approfondie avec SonarQube
  sonarqube-scan:
    # Ce job a besoin que le job bandit-scan soit terminé
    needs: bandit-scan
    name: Scan avec SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        # On doit récupérer l'historique complet pour que SonarQube puisse analyser les nouveaux codes
        with:
          fetch-depth: 0

      - name: Lancement du SonarQube Scanner
        uses: SonarSource/sonar-scanner-run-action@master
        env:
          # Le token secret que tu as configuré dans les paramètres GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # L'URL publique fournie par ngrok
          SONAR_HOST_URL: "https://2949-92-184-105-35.ngrok-free.app"
