# ... (le début du fichier ne change pas)

  # Job 2: Analyse dynamique DAST
  dast-scan:
    name: Scan DAST avec OWASP ZAP
    runs-on: ubuntu-latest
    needs: sast-and-sca-scans
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      # ... (les étapes d'installation et de lancement du serveur ne changent pas)
      - name: Installation de Python et des dépendances
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Lancement des migrations Django
        run: python manage.py migrate
      - name: Lancement de l'application Django en arrière-plan
        run: |
          python manage.py runserver &
          sleep 15

      - name: Scan DAST avec ZAP Baseline
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://127.0.0.1:8000/'
          artifact_name: zap_scan_report
          # LA CORRECTION EST ICI : On désactive la création d'issues
          allow_issue_writing: false