name: Analyse de Sécurité (Bandit & SonarQube)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  bandit-scan:
    name: Scan SAST avec Bandit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      - name: Installation de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit
      - name: Lancement de l'analyse statique avec Bandit
        run: bandit -r . -l low || true

  sonarqube-scan:
    needs: bandit-scan
    name: Scan avec SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # LA CORRECTION EST ICI : on utilise le nom et la version stables et officiels
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: " https://2949-92-184-105-35.ngrok-free.app"
